language: ruby
rvm:
  - 2.2.4
  - jruby-9.0.0.0
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: ruby-head
    - rvm: rbx-19mode
notifications:
  irc: "irc.freenode.org#adhearsion"
